### ISSUE TITLE
More details how to import these examples in Android Studio 2.1.1

### ISSUE THREAD

**Issue by batilei** [googlesamples/android-ndk#260]
Hello, can you provide a bit more hints how to import these examples into Android Studio? I am using Android Studio 2.1.1. When I import this project into Android Studio (I believe they are just pretty standard procedures,(1): import project from exisiting resouces; (2) import project (I select mark all), (3)next, (4) next, (5) Android API 23 Platform). 

Then I saw a bunch of main directory in Android Studio Project pane. After I ran, e.g., "HelloJni", an error shows up:

07-18 15:40:45.495 8243-8243/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.example.hellojni, PID: 8243
                                                 java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.hellojni-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.hellojni-2/lib/x86, /vendor/lib, /system/lib]]] couldn't find "libhello-jni.so"
                                                     at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                     at java.lang.System.loadLibrary(System.java:1076)
                                                     at com.example.hellojni.HelloJni.<clinit>(HelloJni.java:64)
                                                     at java.lang.Class.newInstance(Native Method)
                                                     at android.app.Instrumentation.newActivity(Instrumentation.java:1067)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2317)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by davinctor** [comment]
@batilei Try to import project like sample: `File -> New -> Import Sample -> Find *HelloJni*`
By this way there are less variants where you can fail.

If you importing cmake be sure that you install CMake and LLDB: `File -> Settings -> Appearance and Behaviour -> System Settings -> Android SDK -> SDK Tools (tab) -> Install *CMake* and *LLBD*`

**Comment by ggfan** [comment]
@davinctor is correct, that is the way to import those samples, mainly is to have local.project file created, and your sdk path will be automatically pulled in. ndk path may not be pulled depends whether you asked android studio to install your ndk
- if your ndk is installed by android studio [or an environment variable is set], ndk will be configured
- otherwise, you get an error complaining about ndk not found. At this point update the ndk path and re-sync would get it going
