### ISSUE TITLE
native-media sample is buggy

### ISSUE THREAD

**Issue by proppy** [googlesamples/android-ndk#41]
it crashes when pressing `start/pause java mediaplayer`:
```
V/GLSActivity(17588): AuthDelegateWrapperCreated with selected intent: Intent { cmp=com.google.android.gms/.auth.DefaultAuthDelegateService }
I/ActivityManager(  816): Killing 32743:com.android.musicfx/u0a23 (adj 15): empty #17
I/Icing   (16785): Indexing 32FB3E014AF76EC45535A0157E104AE8D44E1757 from com.google.android.gm
I/Icing   (16785): Indexing done 32FB3E014AF76EC45535A0157E104AE8D44E1757
E/NativeMedia(  972): IOException java.io.IOException: setDataSource failed.
E/MediaPlayer(  972): prepareAsync called in state 1
D/AndroidRuntime(  972): Shutting down VM
--------- beginning of crash
E/AndroidRuntime(  972): FATAL EXCEPTION: main
E/AndroidRuntime(  972): Process: com.example.nativemedia, PID: 972
E/AndroidRuntime(  972): java.lang.IllegalStateException
E/AndroidRuntime(  972): 	at android.media.MediaPlayer.prepareAsync(Native Method)
E/AndroidRuntime(  972): 	at com.example.nativemedia.NativeMedia$7.onClick(NativeMedia.java:227)
E/AndroidRuntime(  972): 	at android.view.View.performClick(View.java:4780)
E/AndroidRuntime(  972): 	at android.view.View$PerformClick.run(View.java:19866)
E/AndroidRuntime(  972): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(  972): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(  972): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(  972): 	at android.app.ActivityThread.main(ActivityThread.java:5257)
E/AndroidRuntime(  972): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(  972): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(  972): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime(  972): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
W/ActivityManager(  816):   Force finishing activity 1 com.example.nativemedia/.NativeMedia
D/audio_hw_primary(  357): out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
D/audio_hw_primary(  357): select_devices: out_snd_device(2: speaker) in_snd_device(0: none)
D/msm8974_platform(  357): platform_send_audio_calibration: sending audio calibration for snd_device(2) acdb_id(15)
E/ACDB-LOADER(  357): Error: ACDB AFE returned = -19
D/audio_hw_primary(  357): enable_snd_device: snd_device(2: speaker)
D/audio_hw_primary(  357): enable_audio_route: apply and update mixer path: low-latency-playback speaker
I/OpenGLRenderer(  816): Initialized EGL, version 1.4
W/ActivityManager(  816): Activity pause timeout for ActivityRecord{12ead1fe u0 com.example.nativemedia/.NativeMedia t8396 f}
I/ActivityManager(  816): Killing 303:com.google.android.apps.enterprise.dmagent/u0a49 (adj 15): empty #17
W/ResourceType( 3731): No package identifier when getting value for resource number 0x00000000
W/PackageManager( 3731): Failure retrieving resources for com.example.nativemedia: Resource ID #0x0
W/ResourceType( 1419): No package identifier when getting value for resource number 0x00000000
W/PackageManager( 1419): Failure retrieving resources for com.example.nativemedia: Resource ID #0x0
D/Webtrends( 1899): Received battery event
D/HeadsetStateMachine(22751): Disconnected process message: 10, size: 0
```

**Comment by ggfan** [comment]
might relate to the test stream: "This sample app requires an MPEG-2 Transport Stream file to be
placed in /sdcard/NativeMedia.ts" [in README.txt]

**Comment by ggfan** [comment]
this one is closed with
https://github.com/googlesamples/android-ndk/pull/182

we are playing from assets, not from /sdcard anymore, clips are inside apk
