### ISSUE TITLE
Memory Leak  in com.sample.camera.basic.CameraActivity

### ISSUE THREAD

**Issue by CainKernel** [googlesamples/android-ndk#464]
there is a memory leak when pressing backPressed button to closed activity, as log with ——
 "android.view.WindowLeaked: Activity com.sample.camera.basic.CameraActivity has leaked window android.widget.PopupWindow$PopupDecorView{dd4d098 V.E...... .......D 0,0-1080,1730} that was originally added here
                                                                            at android.view.ViewRootImpl.<init>(ViewRootImpl.java:418)
                                                                            at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:331)
                                                                            at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
                                                                            at android.widget.PopupWindow.invokePopup(PopupWindow.java:1378)
                                                                            at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1154)
                                                                            at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1121)
                                                                            at com.sample.camera.basic.CameraActivity$2.run(CameraActivity.java:217)
                                                                            at android.os.Handler.handleCallback(Handler.java:751)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)"

I think, in CameraActivity  we should override onDestory() method to dismiss PopupWindow, like this ——

    @Override
    protected void onDestroy() {
        super.onDestroy();
        if (_popupWindow != null && _popupWindow.isShowing()) {
            _popupWindow.dismiss();
        }
    }

**Comment by koyach** [comment]
Thanks for helping.😎

**Comment by ggfan** [comment]
Yeah, that is good catch, tested and it works. onDestroy() is not called I think but it the code should be in. May you send a PR, and I will merge it ( maybe swap the order of this class's clean up code, then call super class's destroy() function, not important ):
```java
@Override
protected void onDestroy() {
    if (_popupWindow != null && _popupWindow.isShowing()) {
        _popupWindow.dismiss();
    }
    super.onDestroy();
}
```
