### ISSUE TITLE
Errors while trying to compile React Native alongside an NDK project

### ISSUE THREAD

**Issue by razvanilin** [googlesamples/android-ndk#535]
Version: r15c
Android Studio: 3.1.3
OS: Windows 10

Hi there,
I recently started to port a React Native + openFrameworks app to Android and I ran into some issues. I'm using the r15c version of android ndk becuase openFrameworks(oF) requires this version. A simple oF app works fine, but the problem arises when I try to add React Native to this project.

I added RN's prerequisites one by one, and ran the project at each step. The error happens when I add RN itself:

```
dependencies {
    addonJavaDependencies(ofRoot()).each { dep ->
        compile(project(path: dep[1] ))
    }
    compile project(path: ':ofAndroidLib')
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile "com.facebook.react:react-native:0.55.4" <---- this line
}
```
I'm quite new at this and these errors don't mean a lot to me. My guess is that RN is not being compiled with the same compiler settings as oF or something along these lines.

This is the error with `gradlew assembleDebug --stacktrace --info`

```
:transformNativeLibsWithStripDebugSymbolForArm7Debug FAILED
:transformNativeLibsWithStripDebugSymbolForArm7Debug (Thread[Daemon worker Thread 7,5,main]) completed. Took 0.484 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformNativeLibsWithStripDebugSymbolForArm7Debug'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':transformNativeLibsWithStripDebugSymbolForArm7Debug'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:32)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:113)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:196)
        at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:193)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:193)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:44)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:29)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.NullPointerException
        at com.android.ide.common.process.ProcessInfoBuilder.setExecutable(ProcessInfoBuilder.java:97)
        at com.android.build.gradle.internal.transforms.StripDebugSymbolTransform.stripFile(StripDebugSymbolTransform.java:223)
        at com.android.build.gradle.internal.transforms.StripDebugSymbolTransform.transform(StripDebugSymbolTransform.java:163)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:185)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:181)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
        at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:176)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:163)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        ... 70 more


BUILD FAILED

Total time: 8.321 secs

```

My whole `gradle.build` file:

```
def ofRoot(){ return '../../../../' }

// Load common functions
apply from: ofRoot()+"libs/openFrameworksCompiled/project/android/common-functions.gradle"

buildscript {
    apply from: "../../../../libs/openFrameworksCompiled/project/android/ndk-verify.gradle"

    repositories {
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
    dependencies {
        // Using the gradle-experimental version that supports c++
        classpath 'com.android.tools.build:gradle-experimental:0.9.3'
        classpath 'com.android.tools.build:gradle:2.3.3'
    }
}

allprojects {
    repositories {
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        maven { url "../node_modules/react-native/android" }
    }
}

apply plugin: 'com.android.model.application'

model {
    android {
        // openFrameworks currently only supports compiling against SDK 19
        compileSdkVersion = 25
        buildToolsVersion = "25.0.3"

        defaultConfig.with {
            minSdkVersion.apiLevel    = 19
            targetSdkVersion.apiLevel = 25
            versionCode     =  1
            versionName     = "1.0"
        }
    }

    android.ndk {
        moduleName = ofAppModuleName()
        toolchain  = buildToolchain()
        stl        = compilerStl()
        platformVersion = "19"
//        abiFilters.addAll(["armeabi-v7a", "x86"])
    }

    android.sources {
        main {
            jni {
                source {
                    srcDirs= appSrcDirs(ofRoot())

                    includes = srcIncludes(ofRoot())
                    excludes = srcExcludes(ofRoot())
                }

                // Link to openFrameworks
                dependencies {
                    project ":openFrameworksProject"  linkage "static"
                }
            }

            manifest {
                source {
                    srcDirs = [ "." ]
                }
            }
            res {
                source {
                    srcDirs = [ "res" ]
                }
            }
            java {
                source {
                    srcDirs = [ "srcJava" ]
                }
            }
            aidl {
                source{
                    srcDirs = ['srcJava']
                }
            }
            renderscript{
                source{
                    srcDirs = ['srcJava']
                }
            }
            jniLibs {
                source {
                    srcDirs = ['libs']
                }
            }
            assets {
                source {
                    srcDirs = ['bin/data'] + addonData(ofRoot())
                }
            }
        }
    }

    android.lintOptions {
        abortOnError  = false
    }

    android.buildTypes {
        release {
            minifyEnabled = false
        }
    }

    // Setup the different types of flavors (arm / x86),
    // and add linker flags based on that
    android.productFlavors {
        getAbis().each { abi ->
            create(getFlavorName(abi)) {
                ndk {
                    abiFilters.add(abi)

                    cppFlags.addAll(coreCppFlags(abi, ofRoot()))
                    cppFlags.addAll(addonCppFlags(abi, ofRoot()))

                    ldLibs.addAll(coreLdLibs(abi, ofRoot()))
                    ldLibs.addAll(addonLdLibs(abi, ofRoot()))

                    ldFlags.addAll(coreLdFlags(abi, ofRoot()))
                    ldFlags.addAll(addonLdFlags(abi, ofRoot()))
                }
            }
        }
    }
}


dependencies {
    addonJavaDependencies(ofRoot()).each { dep ->
        compile(project(path: dep[1] ))
    }
    compile project(path: ':ofAndroidLib')
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile "com.facebook.react:react-native:0.55.4"
}
```

Would really appreciate some help on this one 🙌

**Comment by razvanilin** [comment]
@ggfan the experimental plugin is required for openFrameworks. I can have a look and see if there's a possibility to avoid using it.

**Comment by ggfan** [comment]
Ok got it. you need it then you need it. we will have to see how to get it to work ( not many updates with experimental plugin and it does not work with unified headers. )

I could look at the 2 libs probably some time tomorrow and after.

**Comment by razvanilin** [comment]
@ggfan thanks a lot for the help. For your reference, I tried multiple versions of the experimental plugin and gradle and I only managed to get it to build with the combination of 0.9.3(experimental) and 2.3.3(gradle). I also tried using older versions of Reac Native, but that didn't change the original error.

**Comment by ggfan** [comment]
@razvanilin kind of starting this. knew one thing that [this](https://facebook.github.io/react-native/docs/integration-with-existing-apps.html) works.

will look at the openFramework thing.

**Comment by razvanilin** [comment]
That's the walkthrough I was following when I was trying to set this up. I'm trying to separate the oF and RN into two separate `gradle.build`'s now and see if I get anywhere with that.

**Comment by ggfan** [comment]
got some time on it: does not seem this thing could happen on my end:

- on Mac, openFrameworks generated samples could not built at all (need some efforts to get it to build)
- on Linux, could not get through `yarn add react-native` because our linux does not allow external repo. nothing could be done.

is oF healthy enough to use? some of the build errors are pretty basic during the Mac build.

**Comment by ggfan** [comment]
I am on the way to set it up on my home's windows to continue the thing ( will be a bit slow ). One thing needs to be done is to: change their gradle experimental thing to cmake. That would solve most people's problem.

**Comment by ggfan** [comment]
good thing is that I could see it now.  need to hack to see what is exactly it is complaining or change the gradle-experiemental to cmake and solve the problem forever. I will hack and will let you know.

**Comment by ggfan** [comment]
Hacked on release version 0.10.0, get the projects to build, but I do not know whether the apps are correctly running:

- [androidEmptyExample](https://github.com/ggfan/playground/tree/master/openFrameworks/v_0.10.0/examples/android/androidEmptyExample)
- [androidAccelerometerExample](https://github.com/ggfan/playground/tree/master/openFrameworks/v_0.10.0/examples/android/androidAccelerometerExample)

It is a pure hack: you might carry on from here. I did it on Linux:
- clone the original [OF repo](https://github.com/openframeworks/openFrameworks) somewhere
- download the hacked version [0.10.0](https://github.com/ggfan/playground/tree/master/openFrameworks)
- configure path to yours and run this [script](https://github.com/ggfan/playground/blob/master/openFrameworks/v_0.10.0/scripts/android/pull_from_source.sh) -- it will pull down all of the dependency libs
- Use Android Studio to open the emptyExample (this has repo for ReactNative ) and accelerometerExample, the later one is better; build and load to your device.

the main hacks are:
- [CMakeLists.txt ](https://github.com/ggfan/playground/blob/master/openFrameworks/v_0.10.0/libs/openFrameworks/CMakeLists.txt)for openFrameworks
- [app's CMakeLists.txt ](https://github.com/ggfan/playground/blob/master/openFrameworks/v_0.10.0/examples/android/androidAccelerometerExample/src/CMakeLists.txt)file
- App's [build.gradle](https://github.com/ggfan/playground/blob/master/openFrameworks/v_0.10.0/examples/android/androidAccelerometerExample/build.gradle)
- a little change to [common-function.gradle](https://github.com/ggfan/playground/blob/master/openFrameworks/v_0.10.0/libs/openFrameworksCompiled/project/android/common-functions.gradle)

Again it is a hack, but it would take very little time to get an example of your interest to build:
- just drop the application's CMakeLists.txt over to your example's src/
- and copy over the application's build.gradle to your new example

take a look if you are interested, I will keep it there for a couple weeks ( or moved it out to somewhere ) then delete it ( it is a hack ).  The correct way is to change the files under [template]( https://github.com/ggfan/playground/tree/master/openFrameworks/v_0.10.0/libs/openFrameworksCompiled/project/android), but I could not get ProjectGenerator to build on my debian linux -- out of luck.

**Comment by ggfan** [comment]
@razvanilin the following steps to get it to compile another sample (tried with advanced3D):
- cp androidAccelerometerExample/build.gralde  androidAdvanced3DExample/
- cp androidAccelerometerExample/src/CMakeLists.txt androidAdvanced3DExample/src
- cd ..../v_0.10.0/scripts/android; ./pull_from_source.sh
- Use Android Studio 3.1.x "open" AndroidAcceleromenterExample/build.gradle
- let it update whatever, then open CMakeLists.txt, just add file Grid.cpp, OrthoCamera.cpp Swarm.cpp
- build and run it. works for me.
It is hack and I did not add their gcc equivalent optimization ( -Ofast ) things at all. This should let you play with react-native.  I might hack on more to see how they build projectorGenerator; then add to the stable branch.  enjoy your react-native thing.

**Comment by razvanilin** [comment]
That's amazing, thanks @ggfan !
I went over to the route of using openCV directly with my RN app so I will probably keep it that way since it's a way more solid solution.
I forked your project and I'll give it a try as soon as possible. Maybe we can use this to improve the oF android projects in future versions. Using the experimental gradle is definitely not the way forwards.

**Comment by cerupcat** [comment]
@ggfan did you ever get farther on this? Looking to move my OF project from the experimental plugin to cmake.

**Comment by ggfan** [comment]
not further work on it, sorry.
