### ISSUE TITLE
e.g. NativeMedia is not working. Your examples are just messy, bad docu and buggy. The hole ndk stuff is a pain in the ass.

### ISSUE THREAD

**Issue by hatietz** [googlesamples/android-ndk#582]
0-16 13:45:50.538 8261-8261/com.example.nativemedia E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.nativemedia, PID: 8261
    java.lang.IllegalArgumentException: The surface has been released
        at android.media.MediaPlayer._setVideoSurface(Native Method)
        at android.media.MediaPlayer.setSurface(MediaPlayer.java:742)
        at com.example.nativemedia.NativeMedia$SurfaceHolderVideoSink.useAsSinkForJava(NativeMedia.java:382)
        at com.example.nativemedia.NativeMedia$7.onClick(NativeMedia.java:226)
        at android.view.View.performClick(View.java:4780)
        at android.view.View$PerformClick.run(View.java:19866)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by koyach** [comment]
Ha! Love the title of this!

Are you Linus?

**Comment by ggfan** [comment]
thank you for your comment and your points are very well heard! Will definitely look ways to make it better serve the community.

You definitely are welcome to send patches or add samples, do not hold back:  samples like nativemedia was added by original developer in very early Android days, feel free to send a patch/fix.
