### ISSUE TITLE
Compilation error while running native-media

### ISSUE THREAD

**Issue by zagannath** [googlesamples/android-ndk#60]
While running native-media sample on Android Studio AL-1.4.1 preview2 Im getting below errors.

Executing tasks: [:app:generateArm7DebugAndroidTestSources, :app:generateArm7DebugSources, :app:assembleArm7Debug]

Configuration on demand is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preArm7DebugAndroidTestBuild UP-TO-DATE
:app:prepareArm7DebugAndroidTestDependencies
:app:compileArm7DebugAndroidTestAidl UP-TO-DATE
:app:processArm7DebugAndroidTestManifest UP-TO-DATE
:app:compileArm7DebugAndroidTestRenderscript UP-TO-DATE
:app:generateArm7DebugAndroidTestBuildConfig UP-TO-DATE
:app:generateArm7DebugAndroidTestAssets UP-TO-DATE
:app:mergeArm7DebugAndroidTestAssets UP-TO-DATE
:app:generateArm7DebugAndroidTestResValues UP-TO-DATE
:app:generateArm7DebugAndroidTestResources UP-TO-DATE
:app:mergeArm7DebugAndroidTestResources UP-TO-DATE
:app:processArm7DebugAndroidTestResources UP-TO-DATE
:app:generateArm7DebugAndroidTestSources UP-TO-DATE
:app:preArm7DebugBuild UP-TO-DATE
:app:checkArm7DebugManifest
:app:prepareArm7DebugDependencies
:app:compileArm7DebugAidl UP-TO-DATE
:app:compileArm7DebugRenderscript UP-TO-DATE
:app:generateArm7DebugBuildConfig UP-TO-DATE
:app:generateArm7DebugAssets UP-TO-DATE
:app:mergeArm7DebugAssets UP-TO-DATE
:app:generateArm7DebugResValues UP-TO-DATE
:app:generateArm7DebugResources UP-TO-DATE
:app:mergeArm7DebugResources UP-TO-DATE
:app:processArm7DebugManifest UP-TO-DATE
:app:processArm7DebugResources UP-TO-DATE
:app:generateArm7DebugSources UP-TO-DATE
:app:copyArmeabi-v7aDebugArm7Native-media-jniSharedLibraryGdbServer UP-TO-DATE
:app:createArmeabi-v7aDebugArm7Native-media-jniSharedLibraryGdbsetup
:app:compileArmeabi-v7aDebugArm7Native-media-jniSharedLibraryNative-media-jniMainC UP-TO-DATE
:app:linkArmeabi-v7aDebugArm7Native-media-jniSharedLibrary UP-TO-DATE
:app:stripSymbolsArmeabi-v7aDebugArm7Native-media-jniSharedLibrary UP-TO-DATE
:app:armeabi-v7aDebugArm7Native-media-jniSharedLibrary
:app:processArm7DebugJavaRes UP-TO-DATE
:app:compileArm7DebugJavaWithJavac UP-TO-DATE
:app:compileArm7DebugSources
:app:preDexArm7Debug
:app:dexArm7Debug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
	at com.android.dx.command.dexer.Main.processClass(Main.java:704)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:170)
	at com.android.dx.cf.direct.ClassPathOpener.processDirectory(ClassPathOpener.java:229)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:158)
	at com.android.dx.cf.direct.ClassPathOpener.processDirectory(ClassPathOpener.java:229)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:158)
	at com.android.dx.cf.direct.ClassPathOpener.processDirectory(ClassPathOpener.java:229)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:158)
	at com.android.dx.cf.direct.ClassPathOpener.processDirectory(ClassPathOpener.java:229)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:158)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:632)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)
...while parsing com/example/nativemedia/BuildConfig.class
....
....

25 errors; aborting

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:dexArm7Debug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 13.563 secs

**Comment by ggfan** [comment]
maybe related to #34 ( Java version related ), if you could build others only this one could not built, then it is not related, may you check it out.

**Comment by zagannath** [comment]
I had to download jdk-7u79 for mac and changed jdk location to 1.7 in module settings for fixing this issue.is it not possible to use jdk 1.8 it would have saved my 1 day .. 
Thanks @ggfan

**Comment by ggfan** [comment]
there is a way to make it to work with java 8:
compileOptions.with {
    sourceCompatibility = JavaVersion.VERSION_1_7
    targetCompatibility = JavaVersion.VERSION_1_7
}

this was at the bottom at the #34, sorry I should have pasted here, should have saved you one day. While next time I will paste them here.  Glad you get through it!

**Comment by proppy** [comment]
Happy to continue to discussion in #43. We should update the README.md with instruction on how to set JDK 1.7 and/or add the proper build.gradle workaround.
