### ISSUE TITLE
java.lang.UnsatisfiedLinkError: couldn't find "libecho.so"

### ISSUE THREAD

**Issue by sarathsi** [googlesamples/android-ndk#628]
03-14 12:58:09.660 3421-3421/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.sample.echo, PID: 3421
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.google.sample.echo-5r2ujGmkLiXZyMWynmR0DA==/base.apk", zip file "/data/app/com.google.sample.echo-5r2ujGmkLiXZyMWynmR0DA==/split_lib_dependencies_apk.apk", zip file "/data/app/com.google.sample.echo-5r2ujGmkLiXZyMWynmR0DA==/split_lib_resources_apk.apk", zip file "/data/app/com.google.sample.echo-5r2ujGmkLiXZyMWynmR0DA==/split_lib_slice_0_apk.apk", zip file "/data/app/com.google.sample.echo-5r2ujGmkLiXZyMWynmR0DA==/split_lib_slice_1_apk.apk", zip file "/data/app/com.google.sample.echo-5r2ujGmkLiXZyMWynmR0DA==/split_lib_slice_2_apk.apk", zip file "/data/app/com.google.sample.echo-5r2ujGmkLiXZyMWynmR0DA==/split_lib_slice_3_apk.apk", zip file "/data/app/com.google.sample.echo-5r2ujGmkLiXZyMWynmR0DA==/split_lib_slice_4_apk.apk", zip file "/data/app/com.google.sample.echo-5r2ujGmkLiXZyMWynmR0DA==/split_lib_slice_5_apk.apk", zip file "/data/app/com.google.sample.echo-5r2ujGmkLiXZyMWynmR0DA==/split_lib_slice_6_apk.apk", zip file "/data/app/com.google.sample.echo-5r2ujGmkLiXZyMWynmR0DA==/split_lib_slice_7_apk.apk", zip file "/data/app/com.google.sample.echo-5r2ujGmkLiXZyMWynmR0DA==/split_lib_slice_8_apk.apk", zip file "/data/app/com.google.sample.echo-5r2ujGmkLiXZyMWynmR0DA==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.google.sample.echo-5r2ujGmkLiXZyMWynmR0DA==/lib/arm64, /system/lib64, /product/lib64]]] couldn't find "libecho.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1672)
        at com.google.sample.echo.MainActivity.<clinit>(MainActivity.java:287)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:43)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1224)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3210)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3484)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2123)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7470)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by sarathsi** [comment]
sorry. It was  my mistake. native code was not build. It works now.
